### PR TITLE
Fix bug with handleReturn with latest version of draft-js-plugins

### LINKED ISSUE #12: Plugin stopped working with updated draft-js-plugins-editor 2.0.0-rc2
Hello!

Have you noticed that `draft-js-block-breakout-plugin 1.0.3` stopped working with `draft-js-plugins-editor 2.0.0-rc2`?

The error is:

```
TypeError: getEditorState is not a function. (In 'getEditorState()', 'getEditorState' is undefined)
```

Is it possible to get a new NPM release? Thank you!

### PR DESCRIPTION
**Pull request by Rosey**
Looks like the arguments being passed got modified slightly.

Should fix https://github.com/icelab/draft-js-block-breakout-plugin/issues/12

Also, I ran `npm run build` and `lib/index.js` looks quite different 🤔 Not sure why, this should just be based off latest master. Maybe a build wasn't run after a previous change or something?

### CODE REVIEW

**Comment by makenosound** [comment]
@Rosey Thanks for this! I have been a little too busy to look at properly. Will test this out now and push an update.

> Also, I ran npm run build and lib/index.js looks quite different 🤔 Not sure why, this should just be based off latest master. Maybe a build wasn't run after a previous change or something?

I think this is just babels compilation methods changing between versions, possible that a minor version bump has adjusted the way it outputs certain functions (without there being any behavioural change in the code itself).

**Comment by makenosound** [comment]
Have released this as v2.x. Thanks again, @Rosey!
