### ISSUE TITLE
Plugin stopped working with updated draft-js-plugins-editor 2.0.0-rc2

### ISSUE THREAD

**Issue by martynasjocius** [icelab/draft-js-block-breakout-plugin#12]
Hello!

Have you noticed that `draft-js-block-breakout-plugin 1.0.3` stopped working with `draft-js-plugins-editor 2.0.0-rc2`?

The error is:

```
TypeError: getEditorState is not a function. (In 'getEditorState()', 'getEditorState' is undefined)
```

Is it possible to get a new NPM release? Thank you!

**Comment by saharj** [comment]
I have the same issue and it really affects my project. I would appreciate any update.

**Comment by makenosound** [comment]
Have released this as v2.x.

**Comment by jbonevich** [comment]
Still does not work as of 2.0.1
packages.json:

>     "draft-js": "^0.10.1",
>    "draft-js-autolist-plugin": "^2.0.0",
>    "draft-js-block-breakout-plugin": "^2.0.1",
>    "draft-js-plugins-editor": "^2.0.0-beta1",

**Comment by terencechow** [comment]
*Edit* 
I was having an issue with this not working (no error just does nothing). 

Looking at another closed issue it looks like my version of draft-js-plugins-editor was incompatible.

I had draft-js-plugins-editor  2.0.0-beta1

but I upgraded to draft-js-plugins-editor to 2.0.0-rc5 and it worked
